name       : python-qdarkstyle
version    : 2.8.1
release    : 4
source     :
    - https://github.com/ColinDuquesnoy/QDarkStyleSheet/archive/v2.8.1.tar.gz : bc2f8d2b3644ed660c1267cba314df80a08ddaf28c1b7f701f6cdd6f44f70fdb
homepage   : https://github.com/ColinDuquesnoy/QDarkStyleSheet
license    : MIT
component  : programming.python
summary    : A dark style sheet for QtWidgets application
description: |
    QDarkStyle is a dark stylesheet for Python and Qt applications. This module provides a function to transparently load the stylesheets with the correct rc file.
rundeps    :
    - python-helpdev
    - python-qtpy
build      : |
    %python3_setup
install    : |
    %python3_install
