name       : python-qdarkstyle
version    : '3.1'
release    : 9
source     :
    - https://files.pythonhosted.org/packages/source/Q/QDarkStyle/QDarkStyle-3.1.tar.gz : 600584d625343e0ddd128de08393d3c35637786a49827f174d29aa7caa8279c1
homepage   : https://github.com/ColinDuquesnoy/QDarkStyleSheet
license    : MIT
component  : programming.python
summary    : A dark style sheet for QtWidgets application
description: |
    QDarkStyle is a dark stylesheet for Python and Qt applications. This module provides a function to transparently load the stylesheets with the correct rc file.
rundeps    :
    - python-qtpy
build      : |
    %python3_setup
install    : |
    %python3_install
