name       : python-qdarkstyle
version    : 2.6.5
release    : 1
source     :
    - https://github.com/ColinDuquesnoy/QDarkStyleSheet/archive/2.6.5.tar.gz : d21f455f97b527fe742217419bef991e6502126344fe82712d4f6e7492c21004
license    : MIT
component  : programming.python
summary    : A dark style sheet for QtWidgets application
description: |
    QDarkStyle is a dark stylesheet for Python and Qt applications.
    This module provides a function to transparently load the stylesheets with the correct rc file.
build      : |
    %python3_setup
install    : |
    %python3_install
